### Q1. What is machine learning ? Where and Why you will use machine learning

- Machine learning enables a machine to learn from past data and experiences to improve performance and help to predict things.
- Machine learning gives a view of business patterns which help the company check what are the trends or behaviour of the customer. Machine learning help in the development of new products. Organizations like Facebook, Google uses machine learning models which can handle complex data to provide more accurate and efficient results.
- Nowadays, machine learning applications are everywhere, Siri, Alexa, google home, google allo mobiles app are the few examples of virtual personal assistants which we use.
- Healthcare industry use a Machine learning algorithm to detect skin cancer or retinal image to diagnose diabetes. The Government sector uses machine learning applications to manage and improve cyber security. The E-commerce industry uses machine learning applications to check the shopping history of an individual customer, so based on that they recommend them to purchase similar products

### Q2.What is the difference between data mining and machine learning?

- Data mining is the process of selecting and identifying patterns in large data sets. Machine learning enables the machine to learn from experience or data.
- Data mining teaches a computer to understand unknown patterns in large-scale data sets, Humans use the same data to solve business problems. It is a manual process which need involves human decisions. Machine learning is an AI and enables machines how to learn and analyze from a large dataset and doesn’t require human intervention.
- Data mining involve machine learning algorithms, not all but self-driven cars they are based on machine learning and doesn’t involved data mining.

### Q3. What is normalization and why do you perform? Explain with examples. How do you perform it?

- Normalization is important to scale features to be on a similar scale. This improves the performance and training stability of the model.We can do normalization by different ways.
- Min Max normalization- Formula - (V = value -min/ max- min)
- Z- score Normalization – This type of normalization handles the outlier issue. 
            Formula- (value−μ/ σ )
- Normalization by decimal scaling – In this way we move the decimal point of values of the attribute.
Formula -  (V’ = V/10^j) 

1. Normalization Min Max Example - 

Marks|
-----|
5    |
15   |
25   |

Here minimum value is 5 and maximum value is 25, V is the value of attributes.
newMin is 1 and newMax is 0 

- for marks as 5
  MinMax = (5-5) / (25-5) * (1-0) + 0
        = 0/20 *1 
        = 0
- For marks as 15
  MinMax = (15-5)/(25-5) * (1-0) + 0
          = 10/ 20*1
          = 0.5
- For marks 25 
  MinMax = (25-5) / (25- 5) * (1-0) + 0
           = 1

Marks |MinMax|
-----|-----|
5|0|
15|0.5|
25|1|

### Q4. What is supervised and unsupervised learning? Give some examples

1. Supervised learning is an approach and use by its labeled dataset, these datasets are enabled to classify data or predict results accurately using supervise algorithms. Supervised learning is divided into two types are classification and regression.
For Example:
- Classification – this type of problem uses an algorithm to classify the data accurately, for example, classification of spam messages from your inbox, the machine is trained to predict some features like price, numbers, heights so can predict the stock market prices 
- Regression – This type of supervised learning uses an algorithm that understands the difference between the dependent and independent variables.

2. Unsupervised learning identifies the hidden patterns in data without any labels given 
For Example:
- Clustering – Identifying the group or individual customer shopping behaviour, and based on that they are recommended for the other products to purchase.
- Association- it describes and discovers the large share of the data such as if the person is buying Apple can also tend to buy Orange.

In [1]:
import numpy as np

### Q5 - Create a null vector of size 20 but the 10th value of 20

In [38]:
a = np.zeros(20)


In [39]:
a[9]=20


In [40]:
print('a null vector of size 20 but the 10th value of 20 is')
print(a)

a null vector of size 20 but the 10th value of 20 is
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 20.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.]


### Q6 - Create a vector of positive odd integers less than 100

In [41]:
a = np.arange(1,100)

In [42]:
b = (a[a%2==1])

In [43]:
print('all positive odd intergers less than 100 are')
print(b)

all positive odd intergers less than 100 are
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


### Q7 - Find if there are any values greater than 80

In [81]:
a = np.arange(1,100)
b= (a[a%2==1])
c= (b[b>80])
print('Values greater than 80:')
print(c)


Values greater than 80:
[81 83 85 87 89 91 93 95 97 99]


### Q8 - Remove the values greater than 60 and less than 80

In [85]:
b = np.delete(b, np.where((b >= 60) & (b <= 80))[0], axis=0)
print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 81 83 85 87 89 91 93 95 97 99]


### Q9 -Find the mean, standard deviation of the resulting vector in Q7

In [46]:
mean = np.mean(c)

In [47]:
print("\n Mean of the resulting vector: ", mean)


 Mean of the resulting vector:  90.0


In [48]:
mean = np.std(c)

In [49]:
assert np.allclose(mean, sdeviation)

In [50]:
print("\n standard deviation of resulting vector: ", 1)


 standard deviation of resulting vector:  1


### Q10 -Consider the following vector of values. X <-{8, 14, 9, 15, NA, 8,13, 2,9, NA} . Find the positions of the missing values and how many are there

In [69]:
x = [8, 14, 9, 15, np.nan, 8,13, 2,9, np.nan]
ind=[]
for i in range(0,len(x)):
    if x[i] is np.nan:
        ind.append(i)
        

In [70]:
print(ind)

[4, 9]


In [71]:
x_mean = np.nanmean(x, axis = 0)

In [72]:
print(x_mean)

9.75


### Q11- Replace the missing values with the mean of the non-missing values

In [79]:
x = np.array ([8, 14, 9, 15, np.nan, 8,13, 2,9, np.nan])
x[np.isnan(x)]= 9.75
print(x)

[ 8.   14.    9.   15.    9.75  8.   13.    2.    9.    9.75]


### Q12- Create a 3x3 matrix from the given vector X1 = {2,3,7,1,6,2,3,5,1}

In [51]:
x1 = [2,3,7,1,6,2,3,5,1]


In [52]:
print("Original List:",x1)


Original List: [2, 3, 7, 1, 6, 2, 3, 5, 1]


In [53]:
a = np.array(x1).reshape(3,3)


In [55]:
print("\n 3x3 matrix from the given vector X1 : \n", a)


 3x3 matrix from the given vector X1 : 
 [[2 3 7]
 [1 6 2]
 [3 5 1]]
